version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: $TYPEORM_DATABASE
      MYSQL_ROOT_PASSWORD: $TYPEORM_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    ports:
      - ${TYPEORM_PORT}:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/app/src
    links:
      - db

volumes:
    db-config:
    db-data: